### ISSUE TITLE
[BUG] right-click error 

### ISSUE THREAD

**Issue by Railander** [DJScias/Experiencer2#1]
Message: Usage: local reputationInfo = C_GossipInfo.GetFriendshipReputation(friendshipFactionID)
Time: Sat Nov 11 20:26:28 2023
Count: 5
Stack: Usage: local reputationInfo = C_GossipInfo.GetFriendshipReputation(friendshipFactionID)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetFriendshipReputation'
[string "@Interface/AddOns/Experiencer2/modules/reputation.lua"]:612: in function `GetReputationsMenu'
[string "@Interface/AddOns/Experiencer2/modules/reputation.lua"]:433: in function `GetOptionsMenu'
[string "@Interface/AddOns/Experiencer2/core.lua"]:1272: in function `OpenContextMenu'
[string "@Interface/AddOns/Experiencer2/core.lua"]:1338: in function <Interface/AddOns/Experiencer2/core.lua:1314>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by DJScias** [comment]
Hello there,

Thank you for this bug report, however I'm having trouble reproducing any issues on right-click myself.
Do you have any steps and/or specific reputations you could share me that result into this bug occurring consistently/regularly?

Thanks in advance. 😄

**Comment by DJScias** [comment]
This should be resolved in 5.2.0.
