### ISSUE TITLE
30k instances of bug and climbing in bugsack - attempt to index a number value

### ISSUE THREAD

**Issue by Resika0904** [DJScias/Experiencer2#12]
Expected behavior: it not to have a bazillion errors racking up and causing blizz to yell at me about having too many errors in my UI constantly.

how to reproduce: no idea, it just started doing it today, and continues on reload, switch toons, etc.
error: (this number just keeps going up instantly and climbs forever.):

33020x Experiencer2/modules/reputation.lua:117: attempt to index a number value
[string "@Experiencer2/modules/reputation.lua"]:117: in function `CanLevelUp'
[string "@Experiencer2/core.lua"]:1346: in function `OnUpdate'
[string "@Experiencer2/core.lua"]:1278: in function <Experiencer2/core.lua:1264>

Locals:
self = <table> {
 modules = <table> {
 }
 hasCustomMouseCallback = true
 defaultModuleState = true
 levelUpRequiresAction = true
 db = <table> {
 }
 enabledState = true
 AutoWatchRecent = <table> {
 }
 recentReputations = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 orderedModules = <table> {
 }
 Tracked = "Maruuk Centaur"
 baseName = "Experiencer2"
 initialized = true
 tooltipText = "You can quickly scroll through recently gained reputations by scrolling the mouse wheel while holding down shift key."
 AutoWatchRecentTimeout = 0
 AutoWatchUpdate = 0
 id = "reputation"
 name = "Experiencer2_reputation"
 moduleName = "reputation"
}
factionData = <table> {
 hasBonusRepGain = false
 description = ""
 isHeaderWithRep = false
 isHeader = false
 currentReactionThreshold = 3000
 canSetInactive = false
 atWarWith = false
 isWatched = false
 isCollapsed = false
 canToggleAtWar = false
 nextReactionThreshold = 9000
 factionID = 2503
 name = "Maruuk Centaur"
 currentStanding = 0
 isAccountWide = false
 isChild = false
 reaction = 5
}
(*temporary) = 2209
(*temporary) = 2503
(*temporary) = "attempt to index a number value"

**Comment by DJScias** [comment]
Hey there @Resika0904!

Thank you for reporting this, good catch!
I've just pushed 6.2.1 to CurseForge/Wago/WoWInterface which should take care of this issue.

I'll keep the issue open for a bit so I can see if there's more reports about it popping up after this release goes out.

**Comment by Resika0904** [comment]
Thank YOU so much for keeping this addon alive, you're amazing. <3

**Comment by DJScias** [comment]
> Thank YOU so much for keeping this addon alive, you're amazing. <3

Thank you for reporting the issues! ❤
