### ISSUE TITLE
C_Reputation.GetFactionDataByIndex return nil

### ISSUE THREAD

**Issue by yourapple** [DJScias/Experiencer2#16]
An error occurred in the file reputation.lua. Line 552, C_Reputation.GetFactionDataByIndex returned nil, causing an error.
It can be modified like this

local factionData = C_Reputation.GetFactionDataByIndex(factionIndex) or {0,nil,false,false}

**Comment by DJScias** [comment]
Hello there,

I've just released 6.3.0 to Curseforge/WoWInterface/Wago which should fix this bug.
I'll keep this issue open for a small bit of time so you can see if you can reproduce it again.

Thanks for the report, I really appreciate it!
