### ISSUE TITLE
Switching to paragon weaver rep bugs out

### ISSUE THREAD

**Issue by NoShotz** [DJScias/Experiencer2#17]
It is now just spamming me with errors

```
592x ...eBlizzard_FrameXMLBase/AnimatedStatusBar.lua:167: attempt to perform arithmetic on field 'pendingMax' (a nil value)
[string "@Blizzard_FrameXMLBase/AnimatedStatusBar.lua"]:167: in function `ProcessChanges'
[string "@Blizzard_FrameXMLBase/AnimatedStatusBar.lua"]:109: in function `OnUpdate'
[string "*AnimatedStatusBar.xml:137_OnUpdate"]:1: in function <[string "*AnimatedStatusBar.xml:137_OnUpdate"]:1>

Locals:
self = ExperiencerFrameBarsModule1Main {
 animatedTextureColors = <table> {
 }
 level = 6
 Anim = AnimationGroup {
 }
 pendingValue = 1500
 accumulationTimeout = 0.108000
 BarGain = Texture {
 }
 matchBarValueToAnimation = true
 accumulationTimeoutInterval = 0.350000
 AnimatedTextures = <table> {
 }
 pendingMin = 20000
 SparkBurstMove = Texture {
 }
 BarTrailGlow = Texture {
 }
 matchLevelOnFirstWrap = true
 ColorableTextures = <table> {
 }
 tileTemplateOverlap = 0
 pendingReset = false
 tileTemplateWidth = 37
 spark = ExperiencerFrameBarsModule1MainSpark {
 }
 tileTemplateDelay = 0.150000
 BarGlow = Texture {
 }
 tileTemplate = "AnimatedStatusBarGlowLinesTemplate"
}
levelIsIncreasing = false
min = 17500
max = 20000
oldRange = 2500
(*temporary) = nil
(*temporary) = 20000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'pendingMax' (a nil value)"
```
```
18x Experiencer2/core.lua:583: attempt to perform arithmetic on field 'max' (a nil value)
[string "@Experiencer2/core.lua"]:583: in function `TriggerBufferedUpdate'
[string "@Experiencer2/core.lua"]:1329: in function `OnUpdate'
[string "@Experiencer2/core.lua"]:1313: in function <Experiencer2/core.lua:1299>

Locals:
self = ExperiencerFrameBarsModule1 {
 change = ExperiencerFrameBarsModule1Change {
 }
 highlight = ExperiencerFrameBarsModule1Highlight {
 }
 color = ExperiencerFrameBarsModule1Color {
 }
 hasDataIdChanged = true
 elapsed = 626.702030
 changeTarget = 627
 previousData = <table> {
 }
 textFrame = ExperiencerFrameBarsModule1TextFrame {
 }
 visualSecondary = ExperiencerFrameBarsModule1VisualSecondary {
 }
 module = <table> {
 }
 hasBuffer = true
 main = ExperiencerFrameBarsModule1Main {
 }
 previousModule = <table> {
 }
 moduleId = "reputation"
 visualPrimary = ExperiencerFrameBarsModule1VisualPrimary {
 }
 rested = ExperiencerFrameBarsModule1Rested {
 }
 bufferTimeout = -59.858003
 hasModuleChanged = false
}
instant = nil
data = <table> {
 min = 20000
 current = 1987
 id = 2601
 level = 6
}
valueHasChanged = true
isLoss = false
current = 4487
previous = 627
(*temporary) = 3860
(*temporary) = nil
(*temporary) = <table> {
 1 = Alpha {
 }
 2 = Translation {
 }
 3 = Scale {
 }
 4 = Scale {
 }
 5 = Alpha {
 }
 6 = Alpha {
 }
 7 = Translation {
 }
 8 = Scale {
 }
 9 = Scale {
 }
 10 = Alpha {
 }
 11 = Scale {
 }
 12 = Alpha {
 }
 13 = Alpha {
 }
 14 = Alpha {
 }
 15 = Alpha {
 }
}
(*temporary) = 15
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on field 'max' (a nil value)"
```
```
11x ...eBlizzard_FrameXMLBase/AnimatedStatusBar.lua:124: bad argument #2 to 'SetMinMaxValues' (Usage: self:SetMinMaxValues(minValue, maxValue))
[string "=[C]"]: in function `SetMinMaxValues'
[string "@Blizzard_FrameXMLBase/AnimatedStatusBar.lua"]:124: in function `ProcessChangesInstantly'
[string "@Experiencer2/core.lua"]:592: in function `TriggerBufferedUpdate'
[string "@Experiencer2/core.lua"]:700: in function `Refresh'
[string "@Experiencer2/core.lua"]:331: in function `RefreshModule'
[string "@Experiencer2/core.lua"]:208: in function `Refresh'
[string "@Experiencer2/modules/reputation.lua"]:1033: in function `HandleUpdateFaction'
[string "@Experiencer2/modules/reputation.lua"]:1122: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AlwaysRaw/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <AlwaysRaw/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = ExperiencerFrameBarsModule1Main {
 animatedTextureColors = <table> {
 }
 level = 6
 Anim = AnimationGroup {
 }
 pendingValue = 1500
 accumulationTimeout = 0.350000
 BarGain = Texture {
 }
 matchBarValueToAnimation = true
 accumulationTimeoutInterval = 0.350000
 AnimatedTextures = <table> {
 }
 pendingMin = 20000
 SparkBurstMove = Texture {
 }
 BarTrailGlow = Texture {
 }
 matchLevelOnFirstWrap = true
 ColorableTextures = <table> {
 }
 tileTemplateOverlap = 0
 pendingReset = false
 tileTemplateWidth = 37
 spark = ExperiencerFrameBarsModule1MainSpark {
 }
 tileTemplateDelay = 0.150000
 BarGlow = Texture {
 }
 tileTemplate = "AnimatedStatusBarGlowLinesTemplate"
}
(*temporary) = 20000
(*temporary) = nil
```

presumably this happens to the general and vizier reps as well.

**Comment by NoShotz** [comment]
Here's a video of the issue happening, https://streamable.com/d9rrok

**Comment by DJScias** [comment]
Hello there!

Thank you for this detailed report.
I'll have a look and see what's going on here!

**Comment by DJScias** [comment]
Hello there!

Quick few questions @NoShotz.

You mention Paragon but the rank you have is Collaborator.
I was under the impression Paragon can only happen at the last rank, Mastermind?
Am I misunderstanding something here?

I'm mostly checking this as I can't seem to immediately reproduce this.
I might be able to add some guard-rails for this nil issue however.

But I'd like to make sure I fully understand the pieces here so I know I'm not missing anything:
- Does this happen all the time when switching? Or just when it's switching through recent reputations?
- Are you paragon with these? Or still ranking them up?
If possible, a screenshot/data of what your current rank with min/max value is like so would be nice:
![image](https://github.com/user-attachments/assets/9f3d5523-9562-4de9-a87b-e7a1e9f091a6)

Thanks in advance!

**Comment by NoShotz** [comment]
I've got the mastermind rep for the weaver, not collaborator.
![image](https://github.com/user-attachments/assets/3ed562cd-ca3b-486d-bd47-d9d48196a9f2)

The bug always happens when I switch to to the weaver rep, either from the recent section, or the main rep selector.

**Comment by DJScias** [comment]
Hey there,

Have not forgotten about this.
It's just a bit harder for me to debut his as I have not yet gotten to paragon level for these new reputations.

I'm adding in a few more safeguards for this not to happen, but I will mostly be relying upon you after that I make the changes and that update goes out to see if it's fixed or not.

I'll update the issue once the new version is up.

**Comment by NoShotz** [comment]
Will let you know if I get the issue once the update is out.

Unrelated to the main issue, but for whatever reason, the XP gained during the session is basically always super high, even before I have gotten any XP that session, which kinda makes the gained XP feature not actually work.

![image](https://github.com/user-attachments/assets/5f08c897-add7-40a1-84c2-09c39744ca1b)

**Comment by DJScias** [comment]
Hey there,

I've just pushed 6.3.1 to CurseForge/Wago/WoWInterface which should take care of this issue (hopefully).
It might take a moment for it to get to your addon manager.

Feel free to test it out, and let me know. I can't test it myself unfortunately.
If it still persists, we'll go a bit more of a debug route but here's hoping we don't have to go there!


In regards to your latest issue, is it possible you could make a separate issue for this?
That way once this one is handled, we can separately focus on that one.

However I do am curious what made it rise that high, as I haven't gotten this issue myself either.
But regardless, with an issue up for it I can keep better track of this (And if others get it they can piggyback on it as well).

**Comment by NoShotz** [comment]
Will do.

**Comment by DJScias** [comment]
Perfect, I'm glad to hear this!

I'll be closing this issue, but if something does re-surface feel free to refer to it in this issue.
If necessary, we can make a new one based on that.

Thank you so much for this detailed reporting of the issue, helped me out quite a bit.
