### ISSUE TITLE
Reputation Bar Colors

### ISSUE THREAD

**Issue by susitucker** [DJScias/Experiencer2#4]
Would it be possible to add an option to the reputation bars so that they change color based on the level of reputation in accordance with WoW's reputation level colors? Currently, the reputation bar inherits the color choice of the experience bar itself. 

I love this addon, and I'm grateful that someone has continued its development. Thank you!

**Comment by DJScias** [comment]
Hello there,

I understand what you're asking and I can probably take a look.
Haven't had much time lately though due to WoW: MIsts Remix (limited and all).

**Comment by DJScias** [comment]
This is now in the dev branch, will be made pushed in the next release as I'm still testing it a bit and working on a few other things.

You can toggle "Reputation color" (which will overwrite class/custom color) in `Frame Options`.
![image](https://github.com/DJScias/Experiencer2/assets/439655/527ff71b-d879-49bf-be61-78bcce2cff12)

Some examples, mind you it also works when you have your bar split in two or three.
![image](https://github.com/DJScias/Experiencer2/assets/439655/6488f5e6-b61c-4281-8ce6-21fdab62a1ac)

![image](https://github.com/DJScias/Experiencer2/assets/439655/e2c7954f-0d0c-4d9f-b2fd-1be6e95acd8e)
![image](https://github.com/DJScias/Experiencer2/assets/439655/14a9682d-ad56-49c0-a4fb-490a56997016)
![image](https://github.com/DJScias/Experiencer2/assets/439655/62091c89-0029-414e-a9bf-1f922992f199)

**Comment by susitucker** [comment]
YES!! This is it! OMG you are a star! I can’t wait to see the release. :)

**Comment by DJScias** [comment]
Hello there,

Just pushed the release to Github, Curse should hopefully pick up on it later and push it to users.
