### ISSUE TITLE
Reputation bar keeps resetting

### ISSUE THREAD

**Issue by Demonicka** [DJScias/Experiencer2#9]
## Expected Behavior
It not to reset

## Actual Behavior
Resets to No active watched reputation even though it is set to update with most recent gained reputation

## Steps to Reproduce the Problem

  1.Log into toon
  2.Set reputation bar to show last gained reputation, gain some reputation, see bar not change; log off
  3.Log back in and see that it states "No active watched reputation"

**Comment by Demonicka** [comment]
Also, when you select it to show Dragonflight Reputation, the next time you log back in the option to select Dragonflight vanishes

**Comment by Demonicka** [comment]
This is the error that shows when I manually select each reputation bar in the character window to show as experience bar:

Date: 2024-08-11 00:28:02
ID: 4
Error occured in: Global
Count: 1
Message: Interface/AddOns/Experiencer2/modules/reputation.lua line 541:
   bad argument #1 to 'SetWatchedFactionByID' (Usage: C_Reputation.SetWatchedFactionByID(factionID))
Debug:
   [string "=[C]"]: SetWatchedFactionByID()
   [string "@Interface/AddOns/Experiencer2/modules/reputation.lua"]:541: MenuSetWatchedFactionID()
   [string "@Interface/AddOns/Experiencer2/modules/reputation.lua"]:102: OnMouseWheel()
   [string "@Interface/AddOns/Experiencer2/core.lua"]:1239:
      Interface/AddOns/Experiencer2/core.lua:1234
Locals:
(*temporary) = nil

AddOns:
  Swatter, v9.1.BETA.5.8 (OneMawTime)
  Accountant, v10.2.8
  Ace3, vRelease-r1349
  AceGUI30SharedMediaWidgets, v
  ACP, v3.5.12
  Armory, vv18.0.2
  ArmoryGuildBank, vv18.0.2
  AstralKeys, v4.10
  Auctionator, v11.0.0
  AutoBar, v11.0.0.01
  AverageItemLevel, v10.0.2.1
  Bartender4, v4.15.0
  BeQuiet, v10.1.7.3
  BetterBags, vv0.1.90
  BetterBagsThemes, v1.0.8
  BetterBagsBound, vv1.2.0
  BetterBagsDragonflight, vv1.3.0
  BetterBagsiLvl, v1.1.2
  BetterBagsWarWithin, vv1.0.0
  BetterBagsWorldEvents, v1.3.3
  BlizzMove, vv3.5.34
  BrokerCurrencyflow, vv1.8.6
  CallbackHandler10, v
  CanIMogIt, v11.0.0v2.2
  DBMCore, v11.0.2
  DBMStatusBarTimers, v11.0.2
  Details, v#Details.12829.159
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Experiencer2, v6.0.0
  Hekili, vv11.0.0-1.0.4
  IHearYouRealID, v6.1
  InterruptSay, v3.5.4
  LibDeflate, v1.0.2-release
  LibQTip10, v10.0.7.1
  LibSharedMedia30, v3.0-152
  LibStub, v
  MaxDps, v11.0.3
  Molinari, v110000.116-Release
  MythicDungeonPortals, v1.9
  NOP, vv1.10k
  OmniCC, v11.0.1
  Pawn, v2.9.14
  Plater, vPlater-v583b-Retail
  Plumber, v1.3.3
  Postal, vv4.1.8
  Prat30, v3.9.56
  Quartz, v3.7.12
  RaiderIO, v10.2.7 (v202408102022)
  RaiderIODBUSF, v10.2.7 (v202408102022)
  RaiderIODBUSM, v10.2.7 (v202408102022)
  RaiderIODBUSR, v10.2.7 (v202408102022)
  RemixGemHelper, v1.4.1
  SavedInstances, v11.0.2
  SimpleArmory, v0.0.11
  Simulationcraft, v11.0.0-03
  SlideBar, v9.1.BETA.5.8 (OneMawTime)
  StopResetingMyCameraPlease, v
  VaultButton, v3.3
  WeakAuras, v5.15.4
  WeakAurasArchive, v5.15.4
  WeakAurasCompanion, v5.2.4
  WowheadQuickLink, v2.15.18
  ZPerl, v7.3.0
  ZPerlArcaneBar, v
  ZPerlCustomHighlight, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v11.0.0.110000 <none>
  (ck=807)

**Comment by DJScias** [comment]
Thank you for the detailed report, I'll investigate this!

**Comment by DJScias** [comment]
Hey @Demonicka!

I've just released [6.1.0](https://github.com/DJScias/Experiencer2/releases/tag/6.1.0) to CurseForge which should resolve this.
Could you update to that version with your addon client and see if you can still reproduce it / it there are still issues?

I'll keep the issue opened for a few days so I can hear back from you.

Thanks again for the report, I really appreciate it.

**Comment by DJScias** [comment]
Closed as there has been no further reports of this.

If it does resurface in some shape or form, feel free to make a new issue!
